//Pour ce fichier de test, vous pouvez Run tous les tests d'un seul coup
//Ceci insérera des données en base (POST), et réalisera quelques GET.
//Vous pourrez ainsi voir les résultats en console.

//Une fois le fichier executé, vous pouvez décommenter les quelques requetes DELETE (à la fin du fichier) et les executer pour les tester


// parti ou l'on ajoute beaucoup de données avec des requetes POST

// Pour les compagnie aerienne
### ajout de Air France
POST http://localhost:8080/airlines
Content-Type: application/json

{
  "nom": "Air France",
  "codeIATA": "AF"
}

### ajout de Rayan Air
POST http://localhost:8080/airlines
Content-Type: application/json

{
  "nom": "Rayan Air",
  "codeIATA": "RA"
}

### ajout de Volotea
POST http://localhost:8080/airlines
Content-Type: application/json

{
  "nom": "Volotea",
  "codeIATA": "VO"
}
###Ajout d'un A320

// Pour les avions
POST http://localhost:8080/planes
Content-Type: application/json

{
"numeroImmatriculation": "AF12345",
"modele": "Airbus A320",
"capacite": 200,
"airline": {
"id": 2
}
}
###Ajout d'un A319

POST http://localhost:8080/planes
Content-Type: application/json

{
  "numeroImmatriculation": "RA12345",
  "modele": "Airbus A319",
  "capacite": 185,
  "airline": {
    "id": 3
  }
}
###Ajout d'un A330

POST http://localhost:8080/planes
Content-Type: application/json

{
  "numeroImmatriculation": "VO12359",
  "modele": "Airbus A330",
  "capacite": 485,
  "airline": {
    "id": 4
  }
}

###Ajout du vol AF1001

// Pour les VOLS
POST http://localhost:8080/flights
Content-Type: application/json

{
  "numeroVol": "AF1001",
  "dateDepart": "2025-04-01T10:01:30",
  "dateArrivee": "2025-04-01T14:05:00",
  "statut": "prevu",
  "plane": {
    "id": 2
  },
  "airline": {
    "id": 2
  }
}
###Ajout du vol AF1002
POST http://localhost:8080/flights
Content-Type: application/json

{
  "numeroVol": "AF1002",
  "dateDepart": "2025-04-01T10:01:30",
  "dateArrivee": "2025-04-01T14:05:00",
  "statut": "prevu",
  "plane": {
    "id": 2
  },
  "airline": {
    "id": 2
  }
}


###Ajout du vol AF1003

POST http://localhost:8080/flights
Content-Type: application/json

{
  "numeroVol": "AF1003",
  "dateDepart": "2025-04-01T10:04:00",
  "dateArrivee": "2025-04-01T14:06:00",
  "statut": "prevu",
  "plane": {
    "id": 3
  },
  "airline": {
    "id": 3
  }
}

###Ajout du vol RA1056

POST http://localhost:8080/flights
Content-Type: application/json

{
  "numeroVol": "RA1056",
  "dateDepart": "2025-04-01T10:08:00",
  "dateArrivee": "2025-04-01T14:15:00",
  "statut": "annulee",
  "plane": {
    "id": 4
  },
  "airline": {
    "id": 4
  }
}

### Ajout du passenger Dupont
//pour l'ajout des passagers
POST http://localhost:8080/passengers
Content-Type: application/json

{
  "nom": "Dupont",
  "prenom": "Jean",
  "email": "jean.dupont@gmail.com",
  "numeroPasseport": "FR123456789"
}

### Ajout du passenger Lestylo
POST http://localhost:8080/passengers
Content-Type: application/json

{
  "nom": "Lestylo",
  "prenom": "Marine",
  "email": "marine.lestylo@gmail.com",
  "numeroPasseport": "FR1234568988"
}

### Ajout du passenger Lagiraffe

POST http://localhost:8080/passengers
Content-Type: application/json

{
  "nom": "Lagiraffe",
  "prenom": "Sophie",
  "email": "sophie.lagiraffe@outlook.com",
  "numeroPasseport": "FR1234444444"
}

### Ajout du billet BIL0011

// Pour les billets
POST http://localhost:8080/tickets
Content-Type: application/json

{
  "numeroTicket": "BIL0011",
  "classe": "economique",
  "prix": 250.00,
  "passenger": {
    "id": 2
  },
  "flight": {
    "id": 2
  }
}

### Ajout du billet BIL0011

POST http://localhost:8080/tickets
Content-Type: application/json

{
"numeroTicket": "BIL35551",
"classe": "premiere",
"prix": 435.00,
"passenger": {
"id": 4
},
"flight": {
"id": 2
}
}

### Ajout du billet BIL0023

POST http://localhost:8080/tickets
Content-Type: application/json

{
"numeroTicket": "BIL0023",
"classe": "premiere",
"prix": 650.00,
"passenger": {
"id": 3
},
"flight": {
"id": 1
}
}

### Ajout du billet BIL0089

POST http://localhost:8080/tickets
Content-Type: application/json

{
  "numeroTicket": "BIL0089",
  "classe": "premiere",
  "prix": 1400.00,
  "passenger": {
    "id": 4
  },
  "flight": {
    "id": 4
  }
}
### Ajout d'un bagage cabine
// Pour les bagages

POST http://localhost:8080/luggages
Content-Type: application/json

{
  "poids": 9.0,
  "type": "cabine",
  "passenger": {
    "id": 2
  }
}
### Ajout d'un bagage soute

POST http://localhost:8080/luggages
Content-Type: application/json

{
  "poids": 23.5,
  "type": "soute",
  "passenger": {
    "id": 3
  }
}
### Ajout d'un bagage soute

POST http://localhost:8080/luggages
Content-Type: application/json

{
  "poids": 20.5,
  "type": "soute",
  "passenger": {
    "id": 4
  }
}
### Ajout d'un Pilote Matin


//pour le peronnel

###
POST http://localhost:8080/personnel
Content-Type: application/json

{
"nom": "Matin",
"prenom": "Martin",
"role": "Pilote"
}

### Ajout d'un Steward White

POST http://localhost:8080/personnel
Content-Type: application/json

{
  "nom": "White",
  "prenom": "Walter",
  "role": "Steward"
}

### Ajout d'un Co-pilote Pinkman

POST http://localhost:8080/personnel
Content-Type: application/json

{
  "nom": "Pinkman",
  "prenom": "Jessy",
  "role": "Co-pilote"
}

###Ajout du vol RA1056 en Many to Many
POST http://localhost:8080/flights
Content-Type: application/json

{
  "numeroVol": "AF123",
  "dateDepart": "2025-03-20T10:00:30",
  "dateArrivee": "2025-03-20T12:00:00",
  "statut": "prévu",
  "plane": {
    "id": 2
  },
  "airline": {
    "id": 2
  },
  "personnel": [
    { "id": 2 },
    { "id": 3 }
  ]
}

### Récupérer toutes les compagnies aériennes
GET http://localhost:8080/airlines

### Récupérer une compagnie aérienne par ID
GET http://localhost:8080/airlines/3

### Récupérer les vols d'une compagnie aérienne
GET http://localhost:8080/flights/2

### Récupérer le deuxieme tiquet
GET http://localhost:8080/tickets/2

### Récupérer un bagage et voir son propriétaire
GET http://localhost:8080/luggages/3


### Supprimer la compagnie 3
#DELETE http://localhost:8080/airlines/3

### Supprimer une compagnie aérienne par ID
#DELETE http://localhost:8080/airlines/2

### Supprimer un vol
#DELETE http://localhost:8080/flights/6

### Supprimer le deuxieme tiquet
#DELETE http://localhost:8080/tickets/2

### Supprimer un bagage
#DELETE http://localhost:8080/luggages/3

### vérification
GET http://localhost:8080/luggages/4

### vérification
GET http://localhost:8080/flights/4

